name: Cache cc65
description: Caches cc65 and builds it from source if missing
inputs:
  cc65Ref:
    description: "cc65 git ref (used to checkout a fixed version)"
    required: false
    default: "master"
  cc65Path:
    description: "Path to cache cc65"
    required: false
    default: ${{ github.workspace }}/opt/cc65
runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v4
      id: cache_cc65
      with:
        path: ${{ inputs.cc65Path }}
        key: ${{ runner.os }}-cc65-${{ inputs.cc65Ref }}-${{ hashFiles('.github/actions/cache_cc65/*') }}

    - name: Checkout cc65 repository
      uses: actions/checkout@v4
      if: steps.cache_cc65.outputs.cache-hit != 'true'
      with:
        repository: cc65/cc65
        ref: ${{ inputs.cc65Ref }}
        path: './cc65'

    - name: Build cc65
      if: steps.cache_cc65.outputs.cache-hit != 'true'
      run: |
        cd cc65
        PREFIX=${{ inputs.cc65Path }} make
        PREFIX=${{ inputs.cc65Path }} make install
      shell: bash
