name: Build ROM

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_rom:
    runs-on: ubuntu-24.04
    name: Compile ROM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache cc65
        uses: ./.github/actions/cache_cc65

      - name: Set path for cc65 binaries
        run: |
          echo "${{ github.workspace }}/opt/cc65/bin" >> $GITHUB_PATH

      - name: Build the game
        run: make

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: famidash.nes
          path: BUILD/famidash.nes
